language: ruby
rvm: 2.4.0
script: bundle exec rake test
cache: bundler
bundler_args: "--jobs=3 --retry=3 --without=development"
before_install: gem update --system
matrix:
  include:
  - env: BEAKER_set=centos7 BEAKER_debug=true
    sudo: required
    services: docker
    script: bundle exec rake beaker
  - env: BEAKER_set=stretch BEAKER_debug=true
    sudo: required
    services: docker
    script: bundle exec rake beaker
  - env: BEAKER_set=xenial BEAKER_debug=true
    sudo: required
    services: docker
    script: bundle exec rake beaker
